package com.workmotion.state;

public enum EmployeeState {
    ADDED,
    INCHECK,
    SECURITY_CHECK_STARTED,
    SECURITY_CHECK_FINISHED,
    WORK_PERMIT_CHECK_STARTED,
    WORK_PERMIT_CHECK_PENDING_VERIFICATION,
    WORK_PERMIT_CHECK_FINISHED,
    APPROVED,
    ACTIVE
}
